root /git;
fastcgi_pass unix:/tmp/fcgi.sock;
fastcgi_param SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
fastcgi_param GIT_PROJECT_ROOT /git;
fastcgi_param GIT_HTTP_EXPORT_ALL "";
include fastcgi_params;
