worker_processes 1;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {
    worker_connections 128;
}

http {
    access_log /dev/stdout;
    client_body_temp_path /tmp/client_body;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;
    client_max_body_size 100M;

    server {
        listen 8080;
        server_name _;
        root /git;

        # git-receive-pack (push data) - require auth
        location ~ /git-receive-pack$ {
            auth_basic "Push";
            auth_basic_user_file /etc/nginx/.htpasswd;
            include /etc/nginx/git.conf;
        }

        # Everything else (clone, fetch, etc) - public
        location / {
            include /etc/nginx/git.conf;
        }
    }
}
